name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
    - name: Install libGLEW & SDL2
      run: sudo apt update && sudo apt install -y libglew-dev libsdl2-dev
    - uses: actions/checkout@v3
    - name: Build and run tests (with features)
      run: cargo test --verbose --features disable-screen-frame,disable-system-cursor
    - name: Build and run tests (no features)
      run: cargo test --verbose
    - name: Build examples
      run: cargo build --example rotozoom --example plasma --example sound --example keyboard

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        cache: true
    - name: Build and run tests (with features)
      run: cargo test --verbose --features disable-screen-frame,disable-system-cursor
    - name: Build and run tests (no features)
      run: cargo test --verbose
    - name: Build examples
      run: cargo build --example rotozoom --example plasma --example sound --example keyboard

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy 
          cache: true
      - name: Run Clippy
        run: cargo clippy
        env:
          RUSTFLAGS: -W warnings
